### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by slobo** [tokuhirom/plenv#143]
It would be great to make a new release of `plenv` so that it can be installed by default with macOS package manager `homebrew`. Lastest plenv release - 2.2.0 from 2016, does not properly work with `fish` shell, due to a problem that was fixed in #133.

As a workaround, one needs to remember to install HEAD
```
brew install plenv --HEAD
```

**Comment by tokuhirom** [comment]
please send p-r to homebrew repo.

**Comment by slobo** [comment]
I'm trying to make the formula update, but I think homebrew likes to see an actual version number.

```
$ brew bump-formula-pr --strict plenv --url=https://github.com/tokuhirom/plenv/archive/b2ea2fd.tar.gz --sha256=23d30803254cc59dace5c874f4e56ab976b2e1075098ff74151599af9a926c49
Error: invalid attribute for formula 'plenv': version (nil)
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/formula.rb:258:in `validate_attributes!'
/usr/local/Homebrew/Library/Homebrew/formula.rb:204:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:453:in `find_with_priority'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:48:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:44:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:44:in `formulae'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:89:in `bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

Could you tag a release - (2.2.1 or 2.3.0 or whatever makes sense)? Or is there some showstopper in current master that makes it unstable and not worthy of calling it a release?



Thanks

**Comment by tokuhirom** [comment]
i put 2.3.0 tag~ https://github.com/tokuhirom/plenv/commit/441fd98d0aba27d6523ac156b077d12724768b6b

**Comment by tokuhirom** [comment]
I put 2.3.0 tag https://github.com/tokuhirom/plenv/commit/441fd98d0aba27d6523ac156b077d12724768b6b
